# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/based/tcp-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/based/tcp-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/based/tcp-server/CMakeFiles /home/based/tcp-server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/based/tcp-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

src/core/router.o: src/core/router.cpp.o
.PHONY : src/core/router.o

# target to build an object file
src/core/router.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/router.cpp.o
.PHONY : src/core/router.cpp.o

src/core/router.i: src/core/router.cpp.i
.PHONY : src/core/router.i

# target to preprocess a source file
src/core/router.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/router.cpp.i
.PHONY : src/core/router.cpp.i

src/core/router.s: src/core/router.cpp.s
.PHONY : src/core/router.s

# target to generate assembly for a file
src/core/router.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/router.cpp.s
.PHONY : src/core/router.cpp.s

src/core/trace.o: src/core/trace.cpp.o
.PHONY : src/core/trace.o

# target to build an object file
src/core/trace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/trace.cpp.o
.PHONY : src/core/trace.cpp.o

src/core/trace.i: src/core/trace.cpp.i
.PHONY : src/core/trace.i

# target to preprocess a source file
src/core/trace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/trace.cpp.i
.PHONY : src/core/trace.cpp.i

src/core/trace.s: src/core/trace.cpp.s
.PHONY : src/core/trace.s

# target to generate assembly for a file
src/core/trace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/core/trace.cpp.s
.PHONY : src/core/trace.cpp.s

src/handlers.o: src/handlers.cpp.o
.PHONY : src/handlers.o

# target to build an object file
src/handlers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/handlers.cpp.o
.PHONY : src/handlers.cpp.o

src/handlers.i: src/handlers.cpp.i
.PHONY : src/handlers.i

# target to preprocess a source file
src/handlers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/handlers.cpp.i
.PHONY : src/handlers.cpp.i

src/handlers.s: src/handlers.cpp.s
.PHONY : src/handlers.s

# target to generate assembly for a file
src/handlers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/handlers.cpp.s
.PHONY : src/handlers.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/net/server.o: src/net/server.cpp.o
.PHONY : src/net/server.o

# target to build an object file
src/net/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/server.cpp.o
.PHONY : src/net/server.cpp.o

src/net/server.i: src/net/server.cpp.i
.PHONY : src/net/server.i

# target to preprocess a source file
src/net/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/server.cpp.i
.PHONY : src/net/server.cpp.i

src/net/server.s: src/net/server.cpp.s
.PHONY : src/net/server.s

# target to generate assembly for a file
src/net/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/server.cpp.s
.PHONY : src/net/server.cpp.s

src/net/uring_driver.o: src/net/uring_driver.cpp.o
.PHONY : src/net/uring_driver.o

# target to build an object file
src/net/uring_driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/uring_driver.cpp.o
.PHONY : src/net/uring_driver.cpp.o

src/net/uring_driver.i: src/net/uring_driver.cpp.i
.PHONY : src/net/uring_driver.i

# target to preprocess a source file
src/net/uring_driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/uring_driver.cpp.i
.PHONY : src/net/uring_driver.cpp.i

src/net/uring_driver.s: src/net/uring_driver.cpp.s
.PHONY : src/net/uring_driver.s

# target to generate assembly for a file
src/net/uring_driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/net/uring_driver.cpp.s
.PHONY : src/net/uring_driver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... app"
	@echo "... src/core/router.o"
	@echo "... src/core/router.i"
	@echo "... src/core/router.s"
	@echo "... src/core/trace.o"
	@echo "... src/core/trace.i"
	@echo "... src/core/trace.s"
	@echo "... src/handlers.o"
	@echo "... src/handlers.i"
	@echo "... src/handlers.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/net/server.o"
	@echo "... src/net/server.i"
	@echo "... src/net/server.s"
	@echo "... src/net/uring_driver.o"
	@echo "... src/net/uring_driver.i"
	@echo "... src/net/uring_driver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

